SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [_dta_index_tUrl_5_1966018135__K2_4] ON [mst].[tUrl]
(
	[UrlNo] ASC
)
INCLUDE ( 	[Url]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]


