using System;
using System.Collections.Generic;

namespace UnikktleMentorEngine
{
	public static class SetsumonList
	{
		public static List<Question> GetSetsumonList_JA()
		{
			var list = new List<Question>();

			byte iCnt = 0;
			list.Add(new Question() { Id = iCnt++, Setsumon = "色々な人と知り合いになるのが楽しい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人の中ではいつも後の方に引込んでいる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "難しい問題を考えるのが好き。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "色々違う仕事がしてみたい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "周囲の人とうまく調子を合わせている。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "いつも何かしていないと気がすまない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "世の中の人は他の人に関心をもっていないと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "わけもなく喜んだり悲しんだりする。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人が見ていると仕事ができない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "失敗しないかといつも心配している。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "気持ちが顔に表れやすい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "時々何に対しても興味が無くなる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "知らぬ人と話すときはかたくなる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "グループでは人より率先して働く。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "1人きりでいたいと思うことが時々ある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "計画を立てるよりも早く実行がしたい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "短い時間に沢山の仕事をする自信がある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "正しいと思うことは人にかまわず実行する。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "悪い人がたくさん居ると感じる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "心配で眠れないことがたびたびある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人が来てうるさいと思うことがたびたびある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "なかなか決心がつかず機会を失う事が多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "興奮するとすぐ涙が出る。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人中にいてもふとさびしくなることがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "こちらから進んで友達を作ることが少ない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "会やグループの為に働くのが楽しい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人のすることの裏を考えることが多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "じっと大人しくしているのが苦手。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人に対してはいつも気軽に返事をする。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "目上の人とも遠慮なく議論をする。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "親友でもほんとうには信用していない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "嫌いな人に道で出会うと避けて通る。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "すぐ感情を傷つけられやすい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人から邪魔にされはしないかと心配している。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "早く決心すればよかったと悔やむことが多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "自分をつまらない人間だと思うことがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人目に立つようなことは好まない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "自分で話すより、人の話を聞くことが多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "実行する前に考えなおしてみることが多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "いつも何か刺激を求めている。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "困ることがあっても、ほがらかでいられる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "衝動的になることがある。（自分がおさえられない）。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人が見ていないと大抵の人は怠けると思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "とてもありそうもないことを空想する。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人の品行（行い）が気になる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人前で顔が赤くなることが多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "動揺する事がある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "理由もなく不安になることがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "異性（男なら女）の友達はほとんどいない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "世話役はいつも人に頼む。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "会話の最中にふと考え込むことがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "よく考えずに行動してしまうことが多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "てきぱきと物事をかたずている。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "失礼なことをされると黙っていられない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人の親切には下心がありそうで不安を感じる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "頭がよくなったり、悪くなったりすると感じる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人から見られているようで不安を感じる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "劣等感（他の人より劣る感じ）に悩まされる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "ちょっとしたことでひどく驚くことがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "たびたび物思いに沈むことがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人と広くつきあうのが好き。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "目上の人の前に出るとかたくなる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "何でもよく考えてみないと気がすまない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人といっしょにはしゃぐことが多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "仕事は人よりずっと速い方だと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "平凡に暮らすより何か変わったことがしたい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人は結局利欲の為に働くのだと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "たびたび寝付けずに困ることがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "ちょっとしたことが仕事の邪魔になる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人と違うことは恥ずかしくてできない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "時々気が散って考えがまとまらない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "たびたび過去の失敗をくよくよと考える。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "誰とでもよく話す。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "引っ込み思案だと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "用心深く考える。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "口数が多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "いきいきしていると思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "気が短い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "不満が多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "時々誰かに打ち明け話がしたい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "神経質だと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "すぐうろたえる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "気が変わりやすい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "いつも疲れた気持ちでいる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "新しい友達はなかなかできない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人の扱いがうまいと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "たびたび考え込む。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "お祭り騒ぎが好き。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "新しいことにも直ぐ慣れる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "軽蔑されたと思うとひどく腹が立つ。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "たびたび人の気持ちを確かめてみたいと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "時々ポカンとしていることがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "心配性だと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "困難にぶつかると気持ちがくじける。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "興奮し易い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "たびたび憂鬱になる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "無口だと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "照れ屋だと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "のん気だと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "早とちりがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "いつも機嫌が良い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "色々な世間の活動がしてみたい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "自分はいつも運が悪いと感じる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "空想にふけるのが楽しい。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "気難しい方だと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "何かにつけて自信がない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "すぐ不機嫌になる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "ぼんやり考え込むことがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人中に出てもまごつかない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人前で話すのは気が引ける。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "深く物事を考えることが多い。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "気軽な方だと思う。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "動作はきびきびしている。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "退屈な時は何か強い刺激を求める。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "人は私を十分に認めてくれていないと感じる。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "座っていても気分が落ち着かない。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "小さいことを気に病む。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "あまり迷わず決心がつく。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "感情的になることがある。" });
			list.Add(new Question() { Id = iCnt++, Setsumon = "たびたび元気がなくなる。" });

			return list;
		}

		public static List<Question> GetSetsumonList_EN()
		{
			var list = new List<Question>();

			byte iCnt = 0;
			list.Add(new Question() { Id = iCnt++, Setsumon = "It's fun to get to know a lot of people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Of all the people, I'm always pulling in later." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I like to think about difficult problems." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I want to do different jobs." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "He is in good shape with the people around him." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm sorry if I don't always do something." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I don't think people in the world are interested in other people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "For some reason, they are glad and sad." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "When people are watching you can't work." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm always worried about failing." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Feelings easily appear on the face." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Sometimes I lose interest in anything." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It gets harder to talk to strangers." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "In the group, work ahead of others." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Sometimes I want to be alone." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I want to execute it faster than I make a plan." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I am confident that I will do a lot of work in a short time." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Do whatever you think is right." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I feel that there are many bad people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often can't sleep because of worry." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often find people noisy to come." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It is hard to decide and often lose opportunities." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "As soon as I get excited, I cry." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Even when I'm in a crowd, I sometimes feel lonely." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "There are few people who go from here to make friends." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It's fun to work for a meeting or a group." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often think behind the things that people do." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm not good at keeping quiet." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Always feel free to reply to people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Feel free to discuss with your superiors." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Even my best friend doesn't really trust me." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "If you meet someone you don't like on the road, avoid it." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It is easy to get hurt." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I am worried that people may disturb me." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often regret that I should have decided early." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Sometimes I think of myself as a boring person." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I don't like to stand out." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often listen to people rather than speak for myself." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often think twice before implementing it." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm always looking for some stimulus." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Even if you have a problem, you can leave it alone." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It can be impulsive. (I can't control myself)." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think most people are lazy when they aren't watching." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Fancy things that are very unlikely." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I am concerned about the conduct of people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "The face often turns red in public." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "May be upset." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "You may feel uneasy for no reason." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "There are few friends of the opposite sex (female if male)." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "The caretaker always asks people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I sometimes think about it during a conversation." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often act without thinking." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm doing things quickly." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I can't keep silent when I'm rude." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I feel uneasy about the kindness of people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I feel that my head is getting better or worse." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm worried that people are watching me." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I suffer from inferiority (feeling inferior to other people)." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "A little thing can be terrifying." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often feel pensive." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I like to meet people widely." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It becomes hard to get out in front of a superior person." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm sorry unless I think carefully about everything." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often frolic with people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think work is much faster than people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I want to do something different than living in the ordinary." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think people work after all for lust." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often have trouble sleeping without falling asleep." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "A little thing gets in the way of work." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It's too embarrassing to be different from people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Sometimes distracted and disorganized." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Often think of past failures." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Talk well with anyone." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think it's a retreat." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Think cautiously." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "There are many people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think it's lively." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm short." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I have a lot of complaints." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Sometimes I want to confess to someone." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think it's nervous." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Promptly soon." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It is easy to change your mind." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm always tired." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It's hard to make new friends." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think that people are treated well." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often think about it." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I like festivals." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "You will soon get used to new things." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I get angry when I think I was scorned." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often want to check the feelings of people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Sometimes I'm afraid." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think it's anxious." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Feeling discouraged when you run into difficulties." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Easy to get excited." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often get depressed." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think it's quiet." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think it's a shy person." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think I'm carefree." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "There is an early dust." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm always in a good mood." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I want to do various public activities." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I always feel unlucky." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I enjoy daydreaming." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think it's difficult." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm not confident in anything." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "Get sick soon." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I have a vague idea." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I'm not confused even if I appear in people." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It is distracting to speak in public." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often think deeply." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I think he is a casual person." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "The movement is crisp." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "When I'm bored, I want something strong." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I feel that people don't recognize me enough." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I feel uncomfortable even when I sit down." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I worry about being small." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I can decide without hesitation." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "It can be emotional." });
			list.Add(new Question() { Id = iCnt++, Setsumon = "I often lose energy." });

			return list;
		}
	}
}
