use [UnikktleMentorWeb]
GO


-- <UnikktleMentorU@ƒ†[ƒU[

GRANT EXECUTE ON [dbo].[spAspNetUsers_GetNo] TO [<UnikktleMentorU]
GRANT EXECUTE ON [dbo].[spAspNetUsers_GetNo_FromEmail] TO [<UnikktleMentorU]
GRANT EXECUTE ON [dbo].[spAspNetUsers_Select_FromId] TO [<UnikktleMentorU]
GRANT EXECUTE ON [dbo].[spAspNetUsers_Select_FromUserName] TO [<UnikktleMentorU]

GRANT EXECUTE ON [hst].[spAnswer_Select_Answer] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswer_Select_History] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswerDetail_Select] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswerDetailSupplement_Insert] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswerDetailSupplement_Select] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswerHistory_Insert] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswerHistory_Select] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswerHistory_Select_Desc] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswerHistory_Select_Desc_Top1] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswerHistoryNoLogin_InsertUpdate] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswerHistoryNoLogin_Select] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spAnswerSupplement_Insert] TO [<UnikktleMentorU]
--GRANT EXECUTE ON [hst].[spC01‘e“__Insert] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spC02Œn“’l_Insert] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spC02Œn“’l_Select] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spC02Œn“’l_Select_AllDate] TO [<UnikktleMentorU]
GRANT EXECUTE ON [hst].[spC02Œn“’l_SelectTeamUserAll] TO [<UnikktleMentorU]

GRANT EXECUTE ON [mst].[spAttribute_SelectClass_EN] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spAttribute_SelectClass_JA] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spCareer_Select] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spCareer_Select_JA] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spCareer_SelectAll] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spCareer_SelectAll_JA] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_ChkTeamOwner] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_Delete] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_Insert] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_IsExistence] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_IsExistence_ExcludedNo] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_Select] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_Select_CreatedTeam] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_Select_TeamID] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_SelectAllowApplyToJoinTeam] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_SelectCount] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_SelectCount_CreateUserNo] TO [<UnikktleMentorU]
GRANT EXECUTE ON [mst].[spTeam_Update] TO [<UnikktleMentorU]

GRANT EXECUTE ON [usr].[spFeedback_Insert] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spFeedback_SelectUserNo] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spJoinTeam_Delete] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spJoinTeam_DeleteMember] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spJoinTeam_Insert] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spJoinTeam_Insert_TeamID] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spJoinTeam_Select] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spJoinTeam_SelectCnt] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spJoinTeam_SelectStatus] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spJoinTeam_SelectUser] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spJoinTeam_Update_Status] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spUserSetting_GetOwnedCredit] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spUserSetting_Insert] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spUserSetting_Select] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spUserSetting_SelectProfile] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spUserSetting_Update] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spUserSetting_UpdateIPv4] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spUserSetting_UpdateOwnedCredit] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spUserSetting_UpdateProfile] TO [<UnikktleMentorU]
GRANT EXECUTE ON [usr].[spUserSetting_UpdateProfile2] TO [<UnikktleMentorU]
GO
