use [UnikktleWeb]
GO


-- xxx�@���[�U�[

GRANT EXECUTE ON [pay].[spCreditHistory_Insert] TO [xxx]
GRANT EXECUTE ON [dbo].[spAspNetUsers_GetNo_FromEmail] TO [xxx]
GO


-- <UnikktleWebU�@���[�U�[

GRANT EXECUTE ON [clt].[spCollaborateKeyword_Select] TO [<UnikktleWebU]
GRANT EXECUTE ON [clt].[spCollaborateKeyword_Select_ExcludeNo] TO [<UnikktleWebU]
GRANT EXECUTE ON [clt].[spGetTextWidth] TO [<UnikktleWebU]
GRANT EXECUTE ON [clt].[spKeyword_GetCount] TO [<UnikktleWebU]
GRANT EXECUTE ON [clt].[spKeyword_GetWord] TO [<UnikktleWebU]
GRANT EXECUTE ON [clt].[spKeyword_SelectNo] TO [<UnikktleWebU]
GRANT EXECUTE ON [clt].[spKeyword_Select_Contains] TO [<UnikktleWebU]
GRANT EXECUTE ON [clt].[spKeyword_Select_Freetext] TO [<UnikktleWebU]
GRANT EXECUTE ON [dbo].[spAspNetUsers_GetNo] TO [<UnikktleWebU]
GRANT EXECUTE ON [dbo].[spAspNetUsers_Select_FromId] TO [<UnikktleWebU]
GRANT EXECUTE ON [dbo].[spAspNetUsers_Select_FromUserName] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spAttribute_SelectClass] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spCareer_Select] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spCareer_Select_JA] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spSearchWord_GetNoWithInsert] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spMind_Delete] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spMind_Get_UserNo_AllowOtherEdit] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spMind_Insert] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spMind_Select_Author] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spMind_Select_Contains] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spMind_Select_Freetext] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spMind_SelectNo] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spMind_SelectNo_JsonViewModel] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spMind_Update] TO [<UnikktleWebU]
GRANT EXECUTE ON [mst].[spMindKeyword_GetInsert] TO [<UnikktleWebU]
GRANT EXECUTE ON [pay].[spCreditHistory_GetCnt] TO [<UnikktleWebU]
GRANT EXECUTE ON [pay].[spCreditHistory_SelectUserNo] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelationClickHistory_Insert] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelationWord_Delete] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelationWord_InsertUpdate] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelationWord_Select] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelationWord_SelectCompetingUnitPrices] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelationWord_SelectPR] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelation_Delete] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelation_Get����Count] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelation_Get����Count_����������] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelation_Insert] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelation_Select] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelation_SelectOne] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelation_Update] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverRelation_Update_�����L�������؂�] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearchClickHistory_Insert] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearchWord_Delete] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearchWord_InsertUpdate] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearchWord_Select] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearchWord_SelectCompetingUnitPrices] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearchWord_SelectPR] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearch_Delete] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearch_Get����Count] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearch_Get����Count_����������] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearch_Insert] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearch_Select] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearch_SelectOne] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearch_Update] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spAdverSearch_Update_�����L�������؂�] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spBusiness_Delete] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spBusiness_Insert] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spBusiness_Select] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spBusiness_SelectOne] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spBusiness_Update] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spFeedback_Insert] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spFeedback_SelectUserNo] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spRelationWordClickHistory_Insert] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spUserSetting_GetOwnedCredit] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spUserSetting_Insert] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spUserSetting_Select] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spUserSetting_SelectProfile] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spUserSetting_Update] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spUserSetting_UpdateIPv4] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spUserSetting_UpdateOwnedCredit] TO [<UnikktleWebU]
GRANT EXECUTE ON [usr].[spUserSetting_UpdateProfile] TO [<UnikktleWebU]
GO
